src/Healthy.Web/Controllers/AppointmentController.cs
using System.Data;
using Healthy.Domain.Entities;
using Healthy.Domain.Enums;
using Healthy.Domain.Interfaces;
using Healthy.Web.Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Healthy.Web.Controllers;

public class AppointmentController : Controller
{
    private readonly IBaseRepository<Appointment> _appointmentRepository;
    private readonly IBaseRepository<Patient> _patientRepository;
    private readonly IBaseRepository<Doctor> _doctorRepository;

    public AppointmentController(IBaseRepository<Appointment> appointmentRepository,
        IBaseRepository<Patient> patientRepository, IBaseRepository<Doctor> doctorRepository)
    {
        _appointmentRepository = appointmentRepository;
        _patientRepository = patientRepository;
        _doctorRepository = doctorRepository;
    }

    public async Task<IActionResult> Details(int id, string? modelError = null)
    {
        var appointment = await _appointmentRepository.GetQueryable()
            .Include(i => i.Patient)
            .Include(i => i.Doctor)
            .ThenInclude(d => d.Specialities)
            .FirstOrDefaultAsync(f => f.Id == id);

        if (modelError is not null)
        {
            ModelState.AddModelError(string.Empty, modelError);
        }

        return View(appointment);
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        var (appointments, total) =
            await _appointmentRepository.GetAllAsync(page, pageSize: ViewConstants.PageSize, includeAll: true);

        ViewBag.CurrentPage = page;
        ViewBag.TotalPages = (int)Math.Ceiling((double)total / ViewConstants.PageSize);

        return View(appointments);
    }

    public async Task<IActionResult> Create()
    {
        PopulateDropDownLists();

        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Appointment appointment)
    {
        try
        {
            RemoveModelStateProperties();

            if (ModelState.IsValid)
            {
                var entity = await _appointmentRepository.AddAsync(appointment);
                return RedirectToAction(nameof(Details), new { id = entity.Id });
            }
        }
        catch (Exception e)
        {
            ModelState?.AddModelError(string.Empty, e.Message);
        }
        finally
        {
            PopulateDropDownLists();
        }

        return View(appointment);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var appointment = await _appointmentRepository.GetByIdAsync(id, true);

        var (patients, _) = await _patientRepository.GetAllAsync(1);
        var (doctors, _) = await _doctorRepository.GetAllAsync(1);

        var selectListPatients = new SelectList(patients, nameof(Patient.Id), nameof(Patient.FullName));
        var selectListDoctors = new SelectList(doctors, nameof(Doctor.Id), nameof(Doctor.FullName));

        ViewBag.Patients = selectListPatients;
        ViewBag.Doctors = selectListDoctors;

        return View(appointment);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Appointment appointment)
    {
        try
        {
            RemoveModelStateProperties();

            if (id != appointment.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _appointmentRepository.UpdateAsync(appointment);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState?.AddModelError(string.Empty, e.Message);
        }
        finally
        {
            PopulateDropDownLists();
        }

        return View(appointment);
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _appointmentRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            return RedirectToAction(nameof(Details), new { id = id, modelError = e.Message });
        }
    }

    private async void PopulateDropDownLists()
    {
        var (patients, _) = await _patientRepository.GetAllAsync(1);
        var (doctors, _) = await _doctorRepository.GetAllAsync(1);

        var selectListPatients = new SelectList(patients, nameof(Patient.Id), nameof(Patient.FullName));
        var selectListDoctors = new SelectList(doctors, nameof(Doctor.Id), nameof(Doctor.FullName));

        ViewBag.Patients = selectListPatients;
        ViewBag.Doctors = selectListDoctors;
    }

    private void RemoveModelStateProperties()
    {
        ModelState.Remove(nameof(Appointment.Patient));
        ModelState.Remove(nameof(Appointment.Doctor));
    }

    public async Task<JsonResult> GetCalendarData()
    {
        var query = _appointmentRepository
            .GetQueryable()
            .AsNoTracking()
            .Include(i => i.Patient)
            .Include(i => i.Doctor);

        var appointments = await query
            .ToListAsync();
        var events = new List<object>();

        foreach (var appointment in appointments)
        {
            events.Add(
                new
                {
                    title = $"Consulta {appointment.Id} - {appointment.Patient.FirstName}",
                    start = appointment.Date.ToString("yyyy-MM-ddTHH:mm:ss"),
                    end = appointment.Date.AddMinutes(30).ToString("yyyy-MM-ddTHH:mm:ss"),
                    url = $"/Appointment/Details/{appointment.Id}",
                    backgroundColor = appointment.Status switch
                    {
                        AppointmentStatus.Canceled => "#f44336",
                        AppointmentStatus.Completed => "#4caf50",
                        AppointmentStatus.Scheduled => "#ff9800",
                        AppointmentStatus.Confirmed => "#2196f3",
                        _ => "#2196f3"
                    }
                }
            );
        }

        return Json(events);
    }
}

src/Healthy.Web/Controllers/DoctorController.cs
using Healthy.Domain.Entities;
using Healthy.Domain.Interfaces;
using Healthy.Web.Constants;
using Healthy.Web.Helpers;
using Healthy.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Healthy.Web.Controllers;

public class DoctorController : Controller
{
    private readonly IBaseRepository<Doctor> _doctorRepository;
    private readonly IBaseRepository<Speciality> _specialtyRepository;

    public DoctorController(IBaseRepository<Doctor> doctorRepository, IBaseRepository<Speciality> specialtyRepository)
    {
        _doctorRepository = doctorRepository;
        _specialtyRepository = specialtyRepository;
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        var (doctors, total) =
            await _doctorRepository.GetAllAsync(page, pageSize: ViewConstants.PageSize, orderBy: p => p.FirstName);

        ViewBag.CurrentPage = page;
        ViewBag.TotalPages = (int)Math.Ceiling((double)total / ViewConstants.PageSize);

        return View(doctors);
    }

    public async Task<IActionResult> Details(int id, string? modelError = null)
    {
        var doctor = await _doctorRepository.GetQueryable()
            .Include(i => i.Appointments)
            .ThenInclude(i => i.Patient)
            .Include(i => i.Specialities)
            .FirstOrDefaultAsync(f => f.Id == id);

        if (modelError is not null)
        {
            ModelState.AddModelError(string.Empty, modelError);
        }

        return View(doctor);
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _doctorRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            return RedirectToAction(nameof(Details), new { id, modelError = e.Message });
        }
    }

    public async Task<IActionResult> Edit(int id)
    {
        var doctor = await _doctorRepository.GetByIdAsync(id);
        PopulateSpecialties();

        var doctorViewModel = doctor.Map();

        return View(doctorViewModel);
    }

    public IActionResult Create()
    {
        PopulateSpecialties();
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(DoctorViewModel doctor)
    {
        try
        {
            RemoveModelStateProperties();

            if (ModelState.IsValid)
            {
                var doctorEntity = doctor.Map();
                var specialities = await _specialtyRepository.GetQueryable()
                    .Where(w => doctorEntity.Specialities.Select(s => s.Id).Contains(w.Id))
                    .ToListAsync();
                
                // Database error
                doctorEntity.Specialities = specialities;
                await _doctorRepository.AddAsync(doctorEntity);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState?.AddModelError(string.Empty, e.Message);
        }
        finally
        {
            PopulateSpecialties();
        }

        return View(doctor);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(DoctorViewModel doctor)
    {
        try
        {
            RemoveModelStateProperties();

            if (ModelState.IsValid)
            {
                var doctorEntity = doctor.Map();
                var specialities = await _specialtyRepository.GetQueryable()
                    .Where(w => doctorEntity.Specialities.Select(s => s.Id).Contains(w.Id))
                    .ToListAsync();
                
                // TODO: Unique constraint error
                // Database error
                doctorEntity.Specialities = specialities;
                await _doctorRepository.UpdateAsync(doctorEntity);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState?.AddModelError(string.Empty, e.Message);
        }
        finally
        {
            PopulateSpecialties();
        }

        return View(doctor);
    }

    private async void PopulateSpecialties()
    {
        var (specialties, _) = await _specialtyRepository.GetAllAsync(1, orderBy: s => s.Name);
        ViewBag.Specialities = new MultiSelectList(specialties, nameof(Speciality.Id), nameof(Speciality.Name));
    }

    private void RemoveModelStateProperties()
    {
        ModelState.Remove(nameof(Doctor.Appointments));
        ModelState.Remove(nameof(Doctor.Specialities));
    }
}

src/Healthy.Web/Controllers/PatientController.cs
using Healthy.Domain.Entities;
using Healthy.Domain.Interfaces;
using Healthy.Web.Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Healthy.Web.Controllers;

public class PatientController : Controller
{
    private readonly IBaseRepository<Patient> _repository;

    public PatientController(IBaseRepository<Patient> repository)
    {
        _repository = repository;
    }

    public async Task<IActionResult> Index(int page = 1)
    {
        var (patients, total) =
            await _repository.GetAllAsync(page, pageSize: ViewConstants.PageSize, orderBy: p => p.FirstName);

        ViewBag.CurrentPage = page;
        ViewBag.TotalPages = (int)Math.Ceiling((double)total / ViewConstants.PageSize);

        return View(patients);
    }

    public async Task<IActionResult> Details(int id, string? modelError = null)
    {
        var patient = await _repository.GetQueryable()
            .Include(i => i.Appointments)
            .ThenInclude(i => i.Doctor)
            .FirstOrDefaultAsync(f => f.Id == id);
        
        if (modelError is not null)
        {
            ModelState.AddModelError(string.Empty, modelError);
        }

        return View(patient);
    }

    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Patient patient)
    {
        try
        {
            if (ModelState.IsValid)
            {
                await _repository.AddAsync(patient);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState.AddModelError(string.Empty, e.Message);
        }
        
        return View(patient);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var patient = await _repository.GetByIdAsync(id);
        
        return View(patient);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Patient patient)
    {
        try
        {
            if (id != patient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _repository.UpdateAsync(patient);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState.AddModelError(String.Empty, e.Message);
        }
        
        return View(patient);
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _repository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            return RedirectToAction(nameof(Details), new { id, modelError = e.Message });
        }
    }
}

src/Healthy.Web/Controllers/SpecialityController.cs
using Healthy.Domain.Entities;
using Healthy.Domain.Interfaces;
using Healthy.Web.Constants;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Healthy.Web.Controllers;

public class SpecialityController : Controller
{
    private readonly IBaseRepository<Speciality> _repository;

    public SpecialityController(IBaseRepository<Speciality> repository)
    {
        _repository = repository;
    }
    
    public async Task<IActionResult> Index(int page = 1)
    {
        var (specialities, total) =
            await _repository.GetAllAsync(page, pageSize: ViewConstants.PageSize, orderBy: p => p.Name);

        ViewBag.CurrentPage = page;
        ViewBag.TotalPages = (int)Math.Ceiling((double)total / ViewConstants.PageSize);

        return View(specialities);
    }
    
    public async Task<IActionResult> Details(int id, string? modelError = null)
    {
        var speciality = await _repository.GetQueryable()
            .Include(i => i.Doctors)
            .FirstOrDefaultAsync(f => f.Id == id);

        if (modelError is not null)
        {
            ModelState.AddModelError(string.Empty, modelError);
        }
        
        return View(speciality);
    }
    
    public IActionResult Create()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Speciality speciality)
    {
        try
        {
            if (ModelState.IsValid)
            {
                await _repository.AddAsync(speciality);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState.AddModelError(string.Empty, e.Message);
        }
        
        return View(speciality);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var speciality = await _repository.GetByIdAsync(id);
        
        return View(speciality);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, Speciality speciality)
    {
        try
        {
            if (id != speciality.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                await _repository.UpdateAsync(speciality);
                return RedirectToAction(nameof(Index));
            }
        }
        catch (Exception e)
        {
            ModelState.AddModelError(string.Empty, e.Message);
        }
        
        return View(speciality);
    }

    public async Task<IActionResult> Delete(int id)
    {
        try
        {
            await _repository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
        catch (Exception e)
        {
            return RedirectToAction(nameof(Details), new {id = id, modelError = e.Message});
        }
    }
}

src/Healthy.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Healthy</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Healthy.Web.styles.css" asp-append-version="true"/>
    <icon src="~/favicon.png"/>
</head>

<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Healthy</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Patient" asp-action="Index">Pacientes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Doctor" asp-action="Index">Médicos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Appointment"
                           asp-action="Index">
                            Consultas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Speciality" asp-action="Index">Especialidades</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; @DateTime.Now.Year - Healthy
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>

</html>

src/Healthy.Web/Views/Shared/_Pagination.cshtml
@model (int CurrentPage, int TotalPages, string Action)

<div class="flex justify-content-center">
    <nav aria-label="PageNavigation">
        <ul class="pagination">
            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action(Model.Action, new { page = Model.CurrentPage - 1 })" aria-label="Anterior">
                        <span aria-hidden="true">&laquo;</span>
                        <span class="sr-only">Anterior</span>
                    </a>
                </li>
            }

            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i == Model.CurrentPage)
                {
                    <li class="page-item active">
                        <a class="page-link" href="#">
                            @i <span class="sr-only">(atual)</span>
                        </a>
                    </li>
                }
                else
                {
                    <li class="page-item">
                        <a class="page-link" href="@Url.Action(Model.Action, new { page = i })">@i</a>
                    </li>
                }
            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" href="@Url.Action(Model.Action, new { page = Model.CurrentPage + 1 })" aria-label="Próximo">
                        <span aria-hidden="true">&raquo;</span>
                        <span class="sr-only">Próximo</span>
                    </a>
                </li>
            }
        </ul>
    </nav>
</div>